version: '2'

services:

  nginx:
    image: nginx:1.15.8
    container_name: mood_nginx
    restart: always
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./:/app:ro

  php:
    image: mood_php:latest
    build:
      context: docker/php
    container_name: mood_php
    restart: always
    volumes:
      - ./:/app:ro

  mysql:
    image: mysql:5.7.25
    container_name: mood_mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./docker/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
