version: '2'

services:

  nginx:
    extends:
      file: docker-compose.base.yaml
      service: nginx
    ports:
      - 8080:80

  php:
    extends:
      file: docker-compose.base.yaml
      service: php
    environment:
      SMTP_MAILHUB: "mailcatcher:1025"
      SMTP_REWRITE_DOMAIN: mood.colla.io
      SMTP_HOSTNAME: mood.colla.io
      SMTP_USE_TLS: "NO"

  mysql:
    extends:
      file: docker-compose.base.yaml
      service: mysql

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 8025:1080